lib/ectostuff_web/router.ex
defmodule EctostuffWeb.Router do
  use EctostuffWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", EctostuffWeb do
    pipe_through :browser # Use the default browser stack
    resources "/testtable", TesttableController
    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", EctostuffWeb do
  #   pipe_through :api
  # end
end

lib/ectostuff/application.ex
defmodule Ectostuff.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Ectostuff.Repo, []),
      # Start the endpoint when the application starts
      supervisor(EctostuffWeb.Endpoint, []),
      # Start your own worker by calling: Ectostuff.Worker.start_link(arg1, arg2, arg3)
      # worker(Ectostuff.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Ectostuff.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    EctostuffWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/ectostuff/repo.ex
defmodule Ectostuff.Repo do
  use Ecto.Repo, otp_app: :ectostuff

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/ectostuff_web/controllers/page_controller.ex
defmodule EctostuffWeb.PageController do
  use EctostuffWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/ectostuff_web/controllers/testtable_controller.ex
defmodule EctostuffWeb.TesttableController do
    use EctostuffWeb, :controller

    import Ecto.Query, warn: false
    alias Ectostuff.Repo

    alias Ectostuff.Identity
    alias Ectostuff.Identity.User
    alias EctoStuff.Identity.Adress


    def index(conn, _params) do
        users = Identity.list_users()
        adresses = Identity.list_adresses()
        render(conn, "index.html", users: users, adresses: adresses) 
    end

    def show(conn, %{"id" => id}) do
        user = Identity.get_user!(id)
        adress = Identity.get_adress!(id)
        render(conn, "show.html", user: user, adress: adress)
    end
end

lib/ectostuff_web/views/error_view.ex
defmodule EctostuffWeb.ErrorView do
  use EctostuffWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/ectostuff_web/views/layout_view.ex
defmodule EctostuffWeb.LayoutView do
  use EctostuffWeb, :view
end

lib/ectostuff_web/views/page_view.ex
defmodule EctostuffWeb.PageView do
  use EctostuffWeb, :view
end

lib/ectostuff_web/views/testtable_view.ex
defmodule EctostuffWeb.TesttableView do
    use EctostuffWeb, :view
end

lib/ectostuff_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Ectostuff!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/ectostuff_web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

lib/ectostuff_web/templates/testtable/index.html.eex
<table>
<tr>
<th>ID</th>
<th>First name</th>
<th>Last name</th>
<th>City</th>
<th>Adress</th>
</tr>
<%= for user <- @users do %>
<tr>
<td><%= user.id %></td>
<td><%= user.fname %></td>
<td><%= user.lname %></td>
<%= for adress <- user.adress do %>
<td><%= adress.city %></td>
<td><%= adress.adress %></td>
<% end %>
<td><%= link"show", to: testtable_path(@conn, :show, user) %></td>
</tr>

<% end %>